### ISSUE TITLE
error

### ISSUE THREAD

**Issue by linmingyan123** [zjunlp/MKG_Analogy#1]
when I  run the "main.py",line16, An error was prompted：AttributeError: module 'models' has no attribute 'RobertaUseLabelWord'，what should I do？

**Comment by flow3rdown** [comment]
Thanks for your attention,
This error may be caused by the wrong default argument of `--model_class ` . You can run the bash scripts under `MarT/scripts/` instead of running the `main.py` directly. Here is an example to pretrain the MKGformer model:
```bash
bash scripts/run_pretrain_mkgformer.sh
```
