### ISSUE TITLE
environment problem

### ISSUE THREAD

**Issue by ZouJoelin** [zjunlp/MKG_Analogy#10]
Hello, I am a newbee, and trying to build your project in local, but confronted with the problem below:

I follow the README and run `python IKRL.py`, but it prompt these:
![图片](https://github.com/zjunlp/MKG_Analogy/assets/89274834/c48a564e-7058-4479-9b41-1dfe6a771ccf)

I target the break point at this function call, probably, which is in `TrainDataLoader.py`
![图片](https://github.com/zjunlp/MKG_Analogy/assets/89274834/4d76d829-ce71-4350-a049-fd8d0031332d)
![图片](https://github.com/zjunlp/MKG_Analogy/assets/89274834/3aac7da1-6dc7-402a-bdf4-88d08fe522f0)

I guess it may have some problem to do with Base.so. Do you have any hint how to resolve this?

**Comment by flow3rdown** [comment]
Sorry, I can not reproduce your error. This problem may be related to the environment configuration. You could consult [IKRL](https://github.com/thunlp/IKRL) for guidance on configuring the environment and attempt to test if it can successfully execute using their program.

<img width="522" alt="image" src="https://github.com/zjunlp/MKG_Analogy/assets/46843105/3fd10426-3678-4ffe-a562-a8d451249917">

**Comment by ZouJoelin** [comment]
ok...Thanks for reply
