### ISSUE TITLE
Image path problem

### ISSUE THREAD

**Issue by Vannora9** [zjunlp/MKG_Analogy#12]
Sorry again for bothering you. When I was running image_encoder.py, there is a weird problem:

![image](https://github.com/zjunlp/MKG_Analogy/assets/86482592/ea03fc4b-1afa-4bb0-a79d-c181dda809c3)

I checked the path in the program but I can't find some information...
If it's convenient for you could you give me some hint for it?

Thanks in advance!

**Comment by lcclccc** [comment]
i meet the same problem 
have you solved the problem?

**Comment by Vannora9** [comment]
> i meet the same problem have you solved the problem?

Sadly I am not... I checked the file and found nothing relative to this path...I have no idea how to fix it.

**Comment by flow3rdown** [comment]
Sorry for the error. I have updated the code and you can try again. (Note that put the image data into `MKG_Analogy/M-KGE/RSME/data/images/`)

**Comment by zxlzr** [comment]
Hi, have you solved your issue?
