### ISSUE TITLE
Lower results

### ISSUE THREAD

**Issue by sana-mine** [zjunlp/MKG_Analogy#15]
Nice work! But I reproduce the program's results based on pretrained checkpoints, which are lower than those mentioned in the paper. I would like to know which part of the reason is causing this? And when I saw the image encoding features, the code used a random sampling process. Will it affect the results? Thanks!
![image](https://github.com/zjunlp/MKG_Analogy/assets/78332751/bb7e6e8d-7bf1-4fa8-9b54-497755bfafa0)

**Comment by flow3rdown** [comment]
Thanks for your attention! The hyper-parameters and the image sampling strategy may effect the results, you can refer to issue #9 and issue #8.

**Comment by zxlzr** [comment]
Hi, do you have any further questions?
