### ISSUE TITLE
进程已结束，退出代码为 132 (interrupted by signal 4:SIGILL)

### ISSUE THREAD

**Issue by xdTtt** [zjunlp/MKG_Analogy#16]
按照readme文件运行python IKRL.py出现错误，求助

**Comment by xdTtt** [comment]
请问作者运行代码的操作系统版本及显卡是什么型号的，是不是由于版本问题引起的错误

**Comment by flow3rdown** [comment]
您好，我们的OS版本是Ubuntu 20.04.1 LTS，内存250G，显卡是3090，经测试可以正常运行，您可以看一下具体是在哪个过程出现的问题
