### ISSUE TITLE
在IKRL.py中的代码问题

### ISSUE THREAD

**Issue by bjut-zhangdabao** [zjunlp/MKG_Analogy#17]
尊敬的作者您好，我在运行MKG_Analogy-main\M-KGE\IKRL_TransAE\IKRL.py文件时，该文件的第420行代码：
 with open("data/analogy-img/" + entity + "/avg_embedding.pkl", "rb") as visef:
文件中并没有avg_embedding.pkl，请问：avg_embedding.pkl您能否提供一下，我的邮箱是(2569049998@qq.com),如果可以我将不胜感激。祝您科研顺利！！！

**Comment by flow3rdown** [comment]
您好，感谢您的关注，对于IKRL和TransAE等模型，我们参考了[TransAE](https://github.com/ksolaiman/TransAE)仓库，`avg_embedding.pkl`可以通过[visual_embed.py](https://github.com/zjunlp/MKG_Analogy/blob/main/M-KGE/IKRL_TransAE/visual_embed.py)脚本获取。

**Comment by bjut-zhangdabao** [comment]
尊敬的作者，感谢您的回复和宝贵指导。您的鼓励对我意义非凡。今后的日子里，祝您成果多多，科研顺利。我期待在这充满挑战与机遇的科研道路上，与您共同成长、共同前行。
