### ISSUE TITLE
运行IKRL.py出现问题

### ISSUE THREAD

**Issue by fhcbvdjknl** [zjunlp/MKG_Analogy#18]
尊敬的作者您好，我在运行完visual_embed.py后运行IKRL.py时出现如图所示的问题
![ZSX3I1%D7EYBMB5)PRI_F)V](https://github.com/zjunlp/MKG_Analogy/assets/138900199/bcac89ca-7e45-442c-8d7e-5cfb4240773c)

**Comment by bjut-zhangdabao** [comment]
你好，我也出现了一样的问题，我换了一台服务器并没有出现该问题，我怀疑是Ubuntu的问题：
![屏幕截图 2024-03-23 204536](https://github.com/zjunlp/MKG_Analogy/assets/163393647/e4561933-3593-426d-8154-730f806125fc)
![屏幕截图 2024-03-23 204602](https://github.com/zjunlp/MKG_Analogy/assets/163393647/a6a580bd-8f70-4bc6-a1b4-344e207a4c55)

(第二张截图)Ubuntu~18.04的服务器没有问题
