### ISSUE TITLE
运行TransAE.py出现的问题

### ISSUE THREAD

**Issue by bjut-zhangdabao** [zjunlp/MKG_Analogy#19]
尊敬的作者，您好！
       当我在运行TransAE.py文件时，显示FileNotFoundError: [Errno 2] No such file or directory:  'embedding_weights/textembed_11292_100_2_40.pkl'. 我没有找到生成文本嵌入pkl格式的文件，请问您提供的代码中是否有生成文本嵌入的文件？如果您能指导，我将不胜感激。
     此致
  敬礼
                                                                                                                                                 bjut-zhangdabao
                                                                                                                                                        2024.3.25
附加问题截图：
<img width="641" alt="problem" src="https://github.com/zjunlp/MKG_Analogy/assets/163393647/13c045ff-e1a5-4926-9f2b-4f3d9ff8a077">

**Comment by flow3rdown** [comment]
这个是在保存的时候出现的错误，原因应该是没有创新`embedding_weights`文件夹，你可以尝试创建一个`embedding_weights`空文件夹再运行。

**Comment by bjut-zhangdabao** [comment]
尊敬的作者，感谢您的指导指导，在您的指导下，问题已解决。今后的日子里，祝您披荆斩棘，科研顺利。我非常期待在这充满挑战与机遇的科研道路上与您相逢交流。

**Comment by bjut-zhangdabao** [comment]
作者对科研的的态度，吾辈楷模。
