### ISSUE TITLE
error

### ISSUE THREAD

**Issue by PermanentCedar** [zjunlp/MKG_Analogy#2]
There was an error when I ran cd MarT/tools/encode_images_data.py:  
Can't load image processor for '/zjunlp/lilei/PLMs/clip-vit-base-patch32'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/zjunlp/lilei/PLMs/clip-vit-base-patch32' is the correct path to a directory containing a preprocessor_config.json file
I also couldn't find '/zjunlp/lilei/PLMs/clip-vit-base-patch32' on huggingface.
What shuold I do?

**Comment by flow3rdown** [comment]
We are sorry for the wrong path. We have corrected the path, please pull the code again and use it.
