### ISSUE TITLE
预训练和微调

### ISSUE THREAD

**Issue by fhcbvdjknl** [zjunlp/MKG_Analogy#20]
尊敬的作者您好：
请问这样是不是复现成功，这个预训练的testing是541，微调的testing是11，想知道这个的含义
![0d365b47a136099350c84e4831059db](https://github.com/zjunlp/MKG_Analogy/assets/138900199/d44adb69-e795-4899-b28c-d85f1203ae72)
![6cbc818881f78123ace0c730f75d5cb](https://github.com/zjunlp/MKG_Analogy/assets/138900199/a85668db-8490-4048-b27f-8d10e1720402)

**Comment by flow3rdown** [comment]
您好，可以参考论文中的Table 2和附录中的Table 9，预训练的结果基本一致，微调的结果Hit10低了1个点，其他指标论文中相当或更高一点。

**Comment by fhcbvdjknl** [comment]
您好，我想知道这个预训练里的testing是541，微调里的testing是11，是不是正常情况，还是说我的数据处理有问题

**Comment by flow3rdown** [comment]
是正常情况，两者的评估数据是不同的

**Comment by fhcbvdjknl** [comment]
好的，非常感谢，祝您科研顺利！

**Comment by bjut-zhangdabao** [comment]
> 尊敬的作者您好： 请问这样是不是复现成功，这个预训练的testing是541，微调的testing是11，想知道这个的含义 ![0d365b47a136099350c84e4831059db](https://private-user-images.githubusercontent.com/138900199/325513970-d44adb69-e795-4899-b28c-d85f1203ae72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNjAwMjQsIm5iZiI6MTcxNDA1OTcyNCwicGF0aCI6Ii8xMzg5MDAxOTkvMzI1NTEzOTcwLWQ0NGFkYjY5LWU3OTUtNDg5OS1iMjhjLWQ4NWYxMjAzYWU3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxNTQyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjEwNDI0ZmE3YjI2OTJiYzRkYjQwMWY1YzIzNjE2NzIxYWQwYTZmYWM1NzRjOGJmZDNmNTEyYmNlMmE2YWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZQgzHGytMze8mGEIE53yahLII2aCm3MoMJyFJpPb2yw) ![6cbc818881f78123ace0c730f75d5cb](https://private-user-images.githubusercontent.com/138900199/325514000-a85668db-8490-4048-b27f-8d10e1720402.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNjAwMjQsIm5iZiI6MTcxNDA1OTcyNCwicGF0aCI6Ii8xMzg5MDAxOTkvMzI1NTE0MDAwLWE4NTY2OGRiLTg0OTAtNDA0OC1iMjdmLThkMTBlMTcyMDQwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxNTQyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjVlNDRkNTk3ODg4NmJhMjFiYTJmNWNhODJkM2E3NzMzNGE5NmI4MmM4NjVhMzE3MGE2Zjk5YzZiYWMzODhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5T4oB0g2WaMuSapkGO3FvkOwgqwOcovKTcpy4o1QVVE)

尊敬的学者，您好，请问你在运行encode_image_data.py或者main.py的时候有没有出现如下错误：
<img width="897" alt="捕获" src="https://github.com/zjunlp/MKG_Analogy/assets/163393647/40061798-c746-4778-8c15-ca362f29c842">
请问您是怎么解决的？我的邮箱：2569049998@qq.com

**Comment by HanMinge** [comment]
> > 尊敬的作者您好： 请问这样是不是复现成功，这个预训练的testing是541，微调的testing是11，想知道这个的含义![0d365b47a136099350c84e4831059db](https://private-user-images.githubusercontent.com/138900199/325513970-d44adb69-e795-4899-b28c-d85f1203ae72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNjAwMjQsIm5iZiI6MTcxNDA1OTcyNCwicGF0aCI6Ii8xMzg5MDAxOTkvMzI1NTEzOTcwLWQ0NGFkYjY5LWU3OTUtNDg5OS1iMjhjLWQ4NWYxMjAzYWU3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxNTQyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjEwNDI0ZmE3YjI2OTJiYzRkYjQwMWY1YzIzNjE2NzIxYWQwYTZmYWM1NzRjOGJmZDNmNTEyYmNlMmE2YWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZQgzHGytMze8mGEIE53yahLII2aCm3MoMJyFJpPb2yw) ![6cbc818881f78123ace0c730f75d5cb](https://private-user-images.githubusercontent.com/138900199/325514000-a85668db-8490-4048-b27f-8d10e1720402.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNjAwMjQsIm5iZiI6MTcxNDA1OTcyNCwicGF0aCI6Ii8xMzg5MDAxOTkvMzI1NTE0MDAwLWE4NTY2OGRiLTg0OTAtNDA0OC1iMjdmLThkMTBlMTcyMDQwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxNTQyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjVlNDRkNTk3ODg4NmJhMjFiYTJmNWNhODJkM2E3NzMzNGE5NmI4MmM4NjVhMzE3MGE2Zjk5YzZiYWMzODhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5T4oB0g2WaMuSapkGO3FvkOwgqwOcovKTcpy4o1QVVE)
> 
> 尊敬的学者，您好，请问你在运行encode_image_data.py或者 main.py 的时候有没有出现如下错误： <img alt="捕获" width="897" src="https://private-user-images.githubusercontent.com/163393647/325678879-40061798-c746-4778-8c15-ca362f29c842.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MzczODksIm5iZiI6MTcxNzkzNzA4OSwicGF0aCI6Ii8xNjMzOTM2NDcvMzI1Njc4ODc5LTQwMDYxNzk4LWM3NDYtNDc3OC04YzE1LWNhMzYyZjI5Yzg0Mi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQxMjQ0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWZmNDFlOWViZGZiMDcxODg2NGQ0ZTQwYjZmY2ZhYWY0NDdlNGZjMWJlNWRiZmU3MjZmZTljOTlmMjlkMjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lrmgjs-JDseyAcU6eYtNC72G3-Wgh96Ea-U4krGDAZI"> 请问您是怎么解决的？我的邮箱：[2569049998@qq.com](mailto:2569049998@qq.com)
您好，我也是这样的报错，通过官方的autodl客服回答，也没解决，请问你解决了吗？我的邮箱：2732888967@qq.com

**Comment by flow3rdown** [comment]
> > > 尊敬的作者您好： 请问这样是不是复现成功，这个预训练的testing是541，微调的testing是11，想知道这个的含义![0d365b47a136099350c84e4831059db](https://private-user-images.githubusercontent.com/138900199/325513970-d44adb69-e795-4899-b28c-d85f1203ae72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNjAwMjQsIm5iZiI6MTcxNDA1OTcyNCwicGF0aCI6Ii8xMzg5MDAxOTkvMzI1NTEzOTcwLWQ0NGFkYjY5LWU3OTUtNDg5OS1iMjhjLWQ4NWYxMjAzYWU3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxNTQyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjEwNDI0ZmE3YjI2OTJiYzRkYjQwMWY1YzIzNjE2NzIxYWQwYTZmYWM1NzRjOGJmZDNmNTEyYmNlMmE2YWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZQgzHGytMze8mGEIE53yahLII2aCm3MoMJyFJpPb2yw) ![6cbc818881f78123ace0c730f75d5cb](https://private-user-images.githubusercontent.com/138900199/325514000-a85668db-8490-4048-b27f-8d10e1720402.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNjAwMjQsIm5iZiI6MTcxNDA1OTcyNCwicGF0aCI6Ii8xMzg5MDAxOTkvMzI1NTE0MDAwLWE4NTY2OGRiLTg0OTAtNDA0OC1iMjdmLThkMTBlMTcyMDQwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxNTQyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjVlNDRkNTk3ODg4NmJhMjFiYTJmNWNhODJkM2E3NzMzNGE5NmI4MmM4NjVhMzE3MGE2Zjk5YzZiYWMzODhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5T4oB0g2WaMuSapkGO3FvkOwgqwOcovKTcpy4o1QVVE)
> > 
> > 
> > 尊敬的学者，您好，请问你在运行encode_image_data.py或者 main.py 的时候有没有出现如下错误： <img alt="捕获" width="897" src="https://private-user-images.githubusercontent.com/163393647/325678879-40061798-c746-4778-8c15-ca362f29c842.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MzczODksIm5iZiI6MTcxNzkzNzA4OSwicGF0aCI6Ii8xNjMzOTM2NDcvMzI1Njc4ODc5LTQwMDYxNzk4LWM3NDYtNDc3OC04YzE1LWNhMzYyZjI5Yzg0Mi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQxMjQ0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWZmNDFlOWViZGZiMDcxODg2NGQ0ZTQwYjZmY2ZhYWY0NDdlNGZjMWJlNWRiZmU3MjZmZTljOTlmMjlkMjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lrmgjs-JDseyAcU6eYtNC72G3-Wgh96Ea-U4krGDAZI"> 请问您是怎么解决的？我的邮箱：[2569049998@qq.com](mailto:2569049998@qq.com)
> > 您好，我也是这样的报错，通过官方的autodl客服回答，也没解决，请问你解决了吗？我的邮箱：[2732888967@qq.com](mailto:2732888967@qq.com)

您好，这个错误可能是由于您的网络问题无法从hugginface上下载模型，您可以手动在huggingace下载CLIP模型到本地（下载地址为[link](https://huggingface.co/openai/clip-vit-base-patch32)），之后指定本地模型路径加载模型。此外关于hugginface模型下载的问题您也可以参考一下这个[博客](https://zhuanlan.zhihu.com/p/662947944)。
