### ISSUE TITLE
运行IKRL部分的问题

### ISSUE THREAD

**Issue by qixiaonan1** [zjunlp/MKG_Analogy#21]
在该部分中您定义了IKRL微调和analogy的部分，请问这两部分分别对应什么，如果全为true是否是IKRL下的类比推理，那如果是全为false，那是不是得到的结果就是IKLR的结果

**Comment by flow3rdown** [comment]
您好，finetune为False时为训练实体和关系的embedding，finetune为True时为关系或实体的预测，Analogy控制是否使用ANALOGY模型。

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
