### ISSUE TITLE
question about IKRL

### ISSUE THREAD

**Issue by qixiaonan12** [zjunlp/MKG_Analogy#22]
请问在运行IKRL的部分，是先运行visual_embed文件吗，该文件的用处是什么呀。另外我想直接 利用的是IKRL原本的程序，但是论文给出的并非python代码，请问在这部分可以直接利用吗，或者在写的时候是否有参考可以推荐呢

**Comment by flow3rdown** [comment]
您好，需要先运行`visual_embed.py`将图片进行编码并保存编码后的向量。本项目中IKRL的部分是基于TransAR的代码进行修改的，在算法思路上与IKRL一致，但并未使用IKRL原数据集进行实验，若想复现IKRL或改进其方法，更推荐使用其原代码。

**Comment by qixiaonan12** [comment]
> 您好，需要先运行`visual_embed.py`将图片进行编码并保存编码后的向量。本项目中IKRL的部分是基于TransAR的代码进行修改的，在算法思路上与IKRL一致，但并未使用IKRL原数据集进行实验，若想复现IKRL或改进其方法，更推荐使用其原代码。

那是不是TransAE也是一样的道理呀，TransAE的实现如果复现的话可以根据您这部分的代码改吗

**Comment by qixiaonan1** [comment]
> > 您好，需要先运行`visual_embed.py`将图片进行编码并保存编码后的向量。本项目中IKRL的部分是基于TransAR的代码进行修改的，在算法思路上与IKRL一致，但并未使用IKRL原数据集进行实验，若想复现IKRL或改进其方法，更推荐使用其原代码。
> 
> 那是不是TransAE也是一样的道理呀，TransAE的实现如果复现的话可以根据您这部分的代码改吗

而且我运行visual_embed.py后它并没有保存编码后的向量，请问这是为什么呜呜呜

**Comment by qixiaonan1** [comment]
具体来说它应该是只运行到这一部分

**Comment by flow3rdown** [comment]
> > > 您好，需要先运行`visual_embed.py`将图片进行编码并保存编码后的向量。本项目中IKRL的部分是基于TransAR的代码进行修改的，在算法思路上与IKRL一致，但并未使用IKRL原数据集进行实验，若想复现IKRL或改进其方法，更推荐使用其原代码。
> > 
> > 
> > 那是不是TransAE也是一样的道理呀，TransAE的实现如果复现的话可以根据您这部分的代码改吗
> 
> 而且我运行visual_embed.py后它并没有保存编码后的向量，请问这是为什么呜呜呜

请问有报错吗？您可以贴一下具体的报错信息。

**Comment by flow3rdown** [comment]
> > 您好，需要先运行`visual_embed.py`将图片进行编码并保存编码后的向量。本项目中IKRL的部分是基于TransAR的代码进行修改的，在算法思路上与IKRL一致，但并未使用IKRL原数据集进行实验，若想复现IKRL或改进其方法，更推荐使用其原代码。
> 
> 那是不是TransAE也是一样的道理呀，TransAE的实现如果复现的话可以根据您这部分的代码改吗

是可以的，您也可以参考[TransAE](https://github.com/ksolaiman/TransAE/tree/master)。

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
