### ISSUE TITLE
TransAE finetune和analogy问题

### ISSUE THREAD

**Issue by vandawn** [zjunlp/MKG_Analogy#23]
作者您好:
在运行TransAE的**finetune = True和analogy = True**的版本时，我需要了些许问题，希望得到您的解答：
1. 如果直接设置**finetune = True ＆ analogy = True**时，会报错"missing checkpoint ckpt/analogy/pt_transe.ckpt"，这是否意味着需要先设置**finetune = False ＆ analogy = True**获得checkpoint后才能设置finetune = True来进行关系或实体的预测？
2. 在TransAE的code的1008和1011，checkpoint名是pt_trainse.ckpt，请问这里是多打了一个“i”，正确的文件名是pt_transe.ckpt，还是文件名本身就是pt_trainse.ckpt
![image](https://github.com/zjunlp/MKG_Analogy/assets/34392864/8cb07fe7-6a12-4c3d-a18d-0303867aec4f)
3. 我尝试修改了1008和1011的checkpoint名为pt_transe.ckpt，在运行**finetune = False ＆ analogy = True**得到checkpoint后，重新运行了**finetune = True ＆ analogy = True**，但是得到了报错" size mismatch for ent_re_embeddings.weight: copying a param with shape torch.Size([11292, 400]) from checkpoint, the shape in current model is torch.Size([11292, 200])."
![image](https://github.com/zjunlp/MKG_Analogy/assets/34392864/32f82065-6ecc-4000-a030-0b3f1dd1e2dc)
这似乎是维度不匹配导致的。但是同样的运行思路(先**finetune = False ＆ analogy = True**，后**finetune = False ＆ analogy = True**)在IKRL.py运行时并没有出现同样的问题。

如果能得到您的指导，我将不胜感激。

祝您科研学习顺利。

**Comment by flow3rdown** [comment]
您好，

非常感谢您的关注！

1. 是的，需要先设置`finetune=False`进行实体关系embedding的训练；
2. 此处是多写了一个`i`，感谢指出，现在已经改正；
3. 需要将`TransE`模型定义时的维度保持一致，现在已修改为默认`dim=200`。

**Comment by vandawn** [comment]
感谢您及时的回复和帮助，祝您科研顺利，生活愉快！
