### ISSUE TITLE
loss的值降不下来

### ISSUE THREAD

**Issue by bjut-zhangdabao** [zjunlp/MKG_Analogy#26]
尊敬的李老师，
       您好！
       在您提供的代码里面，我将torch版本升级到了1.12.1，transformers的版本升级到了4.28.0，pytorch-lightning的版本升级到了1.7.0，其他的库包没有变化，显卡型号是4090，然后就出现了损失一直维持在14.9-15的区间范围内。我首先想到的是随机种子和学习率，我尝试着修改这二者的值，发现损失并没有什么改变，这个问题困扰了很久。真诚的恳请您对我的问题提几点建议，我将不甚感激。
       祝您科研工作顺利，期待您在此领域的下一次突破和进展。
                                                                                                                                                       2024.7.30 17：29
                                                                                                                                                        bjut-zhangdabao

<img width="325" alt="捕获" src="https://github.com/user-attachments/assets/c7683b1b-fb54-4d96-bd4c-9af808c49846">

**Comment by flow3rdown** [comment]
您好，应该是pytorch-lightning版本的问题，您可以按照`requirements.txt`中的版本要求配置环境再进行尝试~

**Comment by bjut-zhangdabao** [comment]
感谢您的回复，按照requirements.txt中的版本确实是没有问题的，我在先前已经实现了。这段时间出于好奇，换了一台服务器，并升级了一下各个库的版本才遇到了这样的问题。 
        感谢您的回复，希望您在此领域的进展蒸蒸日上，我将沿着您的科研足迹步步前行。

**Comment by bjut-zhangdabao** [comment]
> 您好，应该是pytorch-lightning版本的问题，您可以按照`requirements.txt`中的版本要求配置环境再进行尝试~

   感谢您的回复，按照requirements.txt中的版本确实是没有问题的，我在先前已经实现了。这段时间出于好奇，换了一台服务器，并升级了一下各个库的版本才遇到了这样的问题。 
    感谢您的回复，希望您在此领域的进展蒸蒸日上，我将沿着您的科研足迹步步前行。
