### ISSUE TITLE
预训练的Transformer模型的层参数如何固定？

### ISSUE THREAD

**Issue by bjut-zhangdabao** [zjunlp/MKG_Analogy#28]
尊敬的作者：
       您好，您在百度[千言万语]技术分享活动做的汇报中提到说：“在预训练的时候，把Transformer其他的层权重都固定掉，只去学习这个word embeding层“，请问，"固定权重操作"在代码中的位置是哪里？
       祝您科研顺利、工作顺利！！！
                                                                                                                                                2024.8.21
                                                                                                                                               bjut-zhangdabao
附图(您在[千言万语]技术活动中的讲到此处的截图)：

<img width="558" alt="千言万语" src="https://github.com/user-attachments/assets/9d47a3bc-7dee-42b6-9423-ff45802fbfeb">

**Comment by flow3rdown** [comment]
您好，可以通过取消注释[此处](https://github.com/zjunlp/MKG_Analogy/blob/a7225385c037a28298f013758bf830119690da9e/MarT/lit_models/transformer.py#L36C9-L38C39)来固定其它层的权重。但在训练资源允许的情况下，还是推荐全量训练，效果会更好一点。

**Comment by bjut-zhangdabao** [comment]
> 您好，可以通过取消注释[此处](https://github.com/zjunlp/MKG_Analogy/blob/a7225385c037a28298f013758bf830119690da9e/MarT/lit_models/transformer.py#L36C9-L38C39)来固定其它层的权重。但在训练资源允许的情况下，还是推荐全量训练，效果会更好一点。

感谢您的热心回复，祝您在科研的道路上不断突破瓶颈，取得更加辉煌的成果！
