### ISSUE TITLE
模型修改

### ISSUE THREAD

**Issue by wzl0422** [zjunlp/MKG_Analogy#29]
尊敬的作者您好，我现在有几个问题想请教一下。我现在想要获得新的数据形式，以便对应模型的输入，因为我想修改一下模型的输入和输出。1、我修改了processor.py中的get_dataset和_create_examples函数，那我如果想得到新的数据形式是要运行data_module.py文件吗？2、我想要知道models下的哪一个.py文件是对应的所提出的模型架构部分？因为我可能还要对应修改该部分模型的输入输出，但是我没有找到哪一个文件对应的是该模型。3、lit_models/transformer.py文件下的training_step方法是不是也要做出对应修改呢？问题有点繁多，还请作者帮助解决！不胜感激！

**Comment by flow3rdown** [comment]
您好，
1. 如果是想要看一下修改后的数据形式的话可以模仿`data_module.py`中对于processor的使用方式自己写代码进行验证；
2. models下的python文件注明了模型的名字，你可以按照你所使用的模型找到对应的python文件进行修改，例如`mkgformer`的模型架构位于`models/modeling_unimo.py`中；
3. training_step是否要修改取决于你数据的形式是如何改造的以及你是否要修改训练逻辑。

**Comment by wzl0422** [comment]
好的，明白了，十分感谢。所以models/modeling_unimo.py中是该模型结构部分。因为mkgformer这个名字没对应上所以我一直存在疑惑。其次，我看关于tail prediction还是写在lit_models/transformer.py中，所以我想知道如果我想要对最后预测部份进行修改的话是不是在training_step中进行对应修改呢？

**Comment by flow3rdown** [comment]
是的，需要修改training_step中对应的过程
