### ISSUE TITLE
fine-tune error

### ISSUE THREAD

**Issue by Q-uassia** [zjunlp/MKG_Analogy#3]
您好，在我下载GoogleDrive提供的ckpt后，复现微调任务时出现报错，好像是ckpt的维度与模型不匹配。
 
![image](https://user-images.githubusercontent.com/77474184/224459119-1720d443-c2c1-4537-a137-55a64484314b.png)

**Comment by flow3rdown** [comment]
您好，请问您使用的是哪个模型的ckpt？

**Comment by Q-uassia** [comment]
MKGformer的

**Comment by flow3rdown** [comment]
应该是没有在运行脚本中加`--only_test`，您可以重新pull一下代码，在`run_finetune_mkgformer.sh`脚本中添加`--only_test`，再进行测试。

**Comment by Q-uassia** [comment]
更新代码并添加--only_test后，还是出现同样的报错信息

**Comment by zxlzr** [comment]
您好，我们已经更新了pretrain_mkgformer.ckpt， 非常抱歉给您带来了不便。
Hi, we have updated the pretrain_mkgformer.ckpt, please download and try it. Sorry for the inconvenience.

**Comment by Q-uassia** [comment]
是的，报错已解决，感谢！
