### ISSUE TITLE
Enviromental problem

### ISSUE THREAD

**Issue by Whnmt** [zjunlp/MKG_Analogy#5]
您好，麻烦问一下跑这个project你们用的windows还是Linux，我mac运行的时候出现了一些问题，windows也是。

**Comment by flow3rdown** [comment]
您好，我们是在Linux上跑的实验，请问您遇到了什么问题呢

**Comment by Whnmt** [comment]
感谢您的回复，我试一下在ubuntu里跑一下实验。
