### ISSUE TITLE
Requirements issue

### ISSUE THREAD

**Issue by buaaneymar** [zjunlp/MKG_Analogy#6]
您好，打扰了。我在pip requirements的时候，出现了could not find torchvision==0.8.0， torch=1.7.0等 (只有一些其他版本)问题，麻烦问一下这种情况我应该怎么解决，安装其他版本的是否可行。希望能得到您的回复与帮助，谢谢！

**Comment by flow3rdown** [comment]
您好，您也可以按照pytorch官网的指令手动安装pytorch，[https://pytorch.org/get-started/previous-versions/](https://pytorch.org/get-started/previous-versions/)

例如，`conda install pytorch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0 cudatoolkit=10.1 -c pytorch`

**Comment by buaaneymar** [comment]
好的，感谢您的回复！

**Comment by buaaneymar** [comment]
> 您好，您也可以按照pytorch官网的指令手动安装pytorch，https://pytorch.org/get-started/previous-versions/
> 
> 例如，`conda install pytorch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0 cudatoolkit=10.1 -c pytorch`

还有一个问题，就是我pip requriments后i，其他包都装了，datasets 2.3.2 depends on tqdm>=4.62.1，The conflict is caused by:
    The user requested tqdm==4.49.0。我可以安装tqdm==4.62以上的版本吗，还是只能4.49。谢谢！！

**Comment by flow3rdown** [comment]
你可以安装高版本tqdm试下，没特殊情况是无影响的。
